# -*- coding: utf-8 -*-
"""House.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UqYkZ7N6s3lOBKXaUQGb0QJkbhIIurY5
"""

import pandas as pd

df = pd.read_csv('F:/1 PROJECT/AI ML/Housing.csv')

df.head()

df.tail()

df.describe()

df.info()

df.isna().sum()

df.head()

list1 = ['mainroad','guestroom','basement', 'hotwaterheating', 'airconditioning', 'prefarea' ]

df[list1] = df[list1].replace({'yes':1,'no':0})

df.head()

df['furnishingstatus'].nunique()

df.tail()

df['furnishingstatus']= df['furnishingstatus'].replace({'furnished':0, 'semi-furnished':1, 'unfurnished':2})

df.head()

from sklearn.preprocessing import StandardScaler

Scaler = StandardScaler()

list2 = [ 'price', 'area']

df[list2]= Scaler.fit_transform(df[list2])

df.head()

df.dtypes

core = df.corr()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,10))
sns.heatmap(core, annot=True, cmap='coolwarm')
plt.show()

df.hist(figsize=(10,10),bins=10)
plt.show()

